### ISSUE TITLE
Install Phabricator on quantix3.snoarmy.me

### ISSUE THREAD

**Issue by Reception123** [revi/issues#5]
Install Phabricator on quantix3.snoarmy.me

**Comment by revi** [comment]
Required stuff before I can proceed;

 -[ ] Grant me SSH access with write access to the webserver directory (if you can trust me fine wth sudo)
 -[ ] Have Ubuntu 14.04 LTS.

And then I can do the install/initial config.

**Comment by Reception123** [comment]
Quantix3 has 14.04.03 LTS, so that can be checked off.
NDKilla working on sudo

**Comment by revi** [comment]
Now installing.

**Comment by revi** [comment]
Done now. Config is mostly done too.
